### ISSUE TITLE
There is no xcode.Project file.  In this case, How can I run this example in Mac OSX? 

### ISSUE THREAD

**Issue by bemoregt** [kitschpatrol/ofxASR#1]
Hi, @kitschpatrol 

There is no xcode.Project file. 
In this case, How can I run this example in Mac OSX?  

Thanks in advance ~

**Comment by kitschpatrol** [comment]
Hi — good question... unfortunately I haven't used this in years and don't have a recent Xcode project file handy.

If I had to get it running again, I would build an empty OF project using the project generator (specifying use of the addon)... and then hopefully the addon's libraries would be linked correctly via the info in install.xml. I'd then merge in the code from the example project.

Sorry for the inconvenience. If you get it working, I'd love a PR!
